name: Testflight
on:
  push:
    branches:
      - main
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
jobs:
  testflight:
    runs-on: macos-12
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "13.3"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6.8"
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: bundle install
      - name: Install pnpm dependencies
        run: |
          pnpm install --frozen-lockfile
      - name: Build extension js
        run: |
          pnpm turbo run build
      - name: Submit our build to testflight
        run: bundle exec fastlane submit_build
        env:
          APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
          APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
          APPLE_KEY_CONTENT: ${{ secrets.APPLE_KEY_CONTENT }}
          GIT_AUTHORIZATION: ${{ secrets.BOT_TOKEN }}
          TEMP_KEYCHAIN_PASSWORD: ${{ secrets.TEMP_KEYCHAIN_PASSWORD }}
          TEMP_KEYCHAIN_USER: ${{ secrets.TEMP_KEYCHAIN_USER }}
          DEVELOPER_APP_ID: ${{ secrets.DEVELOPER_APP_ID }}
          DEVELOPER_APP_IDENTIFIER: ${{ secrets.DEVELOPER_APP_IDENTIFIER }}
          PROVISIONING_PROFILE_SPECIFIER: ${{ secrets.PROVISIONING_PROFILE_SPECIFIER }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ secrets.DEVELOPER_PORTAL_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD: true
      - name: Commit updated build number
        if: always()
        uses: stefanzweifel/git-auto-commit-action@v4
